/** Frozen topic inputs, not authored scene code. Keep these prompts stable across reruns. */
export const showcaseTopics = [
  ['fourier', 'Fourier epicycles', 'Mathematics', '2d', 'Reconstruct a closed asymmetric curve with at least eight complex Fourier terms. Show rotating vectors, their chained endpoint, and the growing trace in one coherent view. Derive every endpoint from the same coefficients; retain the full trace at the end.'],
  ['convolution', 'Continuous convolution', 'Mathematics', '2d', 'Slide a compact triangular kernel across a two-pulse signal. Show the pointwise product, shaded overlap and corresponding convolution output growing together. Compute the integral numerically from the displayed functions; make the input-to-output correspondence visible.'],
  ['mobius', 'Complex Möbius map', 'Mathematics', '2d', 'Transform a complex-plane grid with w=(z-1)/(z+1). Track a selected circle and point continuously; handle the pole at z=-1 by splitting or clipping paths rather than joining across infinity. Show the original and mapped geometry with a clear correspondence.'],
  ['svd', 'Singular-value decomposition', 'Mathematics', '2d', 'Show a nonsymmetric real 2x2 matrix acting on a unit circle and grid via its SVD: rotate, stretch along principal axes, rotate. Use one actual matrix and consistent factors, preserve reference vectors, and show the final ellipse and transformed basis.'],
  ['bezier', 'Bicubic surface patch', 'Geometry', '3d', 'Show a bicubic Bézier surface with a 4x4 control lattice. Move one interior control point and deform the entire surface from Bernstein weights; retain boundary continuity, mesh topology and a visible local normal. Use a restrained parametric grid.'],
  ['torus-knot', 'Torus knot and moving frame', 'Geometry', '3d', 'Construct a smooth (2,3) torus knot as a swept tube, with a small moving tangent-normal-binormal frame. Make the knot pass correctly over and under itself, with stable tube cross-section and a restrained matte material. No self-intersection caused by incorrect closure.'],
  ['interference', 'Two-source wave interference', 'Physics', '2d', 'Visualize two coherent circular wave sources, their superposed scalar field and fixed interference nodes. Use one shared wave formula and synchronized time; show constructive and destructive interference through geometry or field intensity, not a page of labels.'],
  ['electromagnetic', 'Electromagnetic plane wave', 'Physics', '3d', 'Show a linearly polarized traveling plane wave: orthogonal electric and magnetic vectors in phase, both perpendicular to propagation. Use synchronized sinusoidal samples and restrained E/B colors. Field arrows must reverse direction through zero; make propagation direction unmistakable.'],
  ['kepler', 'Kepler orbit and equal areas', 'Astronomy', '3d', 'Show an eccentric bound Kepler orbit around a focus, integrated or solved with correct nonuniform orbital speed. Sweep equal-time area sectors near periapsis and apoapsis. Use a restrained orbital plane and a real 3D planet; do not mistake the ellipse center for the focus.'],
  ['dipole', 'Electric dipole field', 'Physics', '3d', 'Show equal positive and negative point charges with a sparse 3D vector field and smooth field-line traces calculated from their inverse-square fields. Terminate lines near singularities, keep arrow direction correct and expose depth without clutter.'],
  ['snell', 'Refraction through a prism', 'Optics', '3d', 'Trace several visible-light rays through a triangular glass prism using Snell law at both faces and wavelength-dependent refractive indices. Show entry, interior and exit segments with correct surface normals and a subtle cutaway or transparency strategy that does not hide rays. Use an explicitly illustrative dispersion model.'],
  ['gyroscope', 'Gyroscope orientation', 'Mechanics', '3d', 'Show a spinning gyroscope rotor, axle and support with a clearly labeled idealized prescribed precession. Distinguish fast spin from slow precession using coherent transforms, a small angular-momentum arrow and fixed pivot. Do not claim a full torque-integrated simulation.'],
  ['salt-crystal', 'Rock-salt crystal lattice', 'Chemistry', '3d', 'Show a small NaCl rock-salt lattice with alternating ion sublattices, a selected unit cell and octahedral sixfold nearest-neighbor coordination around an interior ion. Use atoms as spheres, explain display radius scaling locally, and avoid pretending this is a molecular NaCl dimer or measured dynamics.'],
  ['lipid', 'Membrane and ion channel', 'Biology', '3d', 'Build a molecular-scale schematic of a lipid bilayer with hydrophilic heads outside and paired hydrophobic tails inward, plus a membrane-spanning pore. Move a few ions through the pore, not through lipid tails. Label geometry as schematic; maintain recognizable membrane thickness and depth.'],
  ['capsid', 'Icosahedral viral capsid', 'Biology', '3d', 'Show an idealized icosahedral capsid assembled from repeating triangular subunits with correct closed topology. Open a small contiguous section to reveal an interior nucleic-acid schematic. Distinguish this geometric model from a specific experimentally resolved virus; avoid unsupported atomic detail.'],
  ['protein', 'Protein alpha helix', 'Biology', '3d', 'Show an idealized alpha-helical peptide backbone with consistent 3.6-residue-per-turn geometry and selected i-to-i+4 hydrogen-bond relationships. Use clear molecular backbone geometry with side-chain direction cues, not a generic spring. Label idealized geometry and avoid claiming deposited atom coordinates.'],
  ['planetary', 'Planetary gear train', 'Engineering', '3d', 'Show a sun gear, three planets, fixed internal ring and moving carrier. Choose compatible tooth counts and derive spin/orbit rates from the gear constraint. Teeth must engage without obviously passing through one another; preserve planet spacing and use subtle machined-metal texture.'],
  ['crank', 'Slider-crank mechanism', 'Engineering', '3d', 'Build an oblique cutaway slider-crank with crankshaft, flywheel, rigid connecting rod, wrist pin and constrained piston. Derive piston travel from fixed rod length and crank angle, preserve pin connections throughout a cycle, and use restrained metal materials.'],
  ['robot', 'Three-joint robot arm', 'Robotics', '3d', 'Show a three-revolute-joint robot arm following a smooth end-effector path through a bounded workspace. Derive links and end-effector from one forward-kinematics chain; show local joint axes, keep links rigid and joints connected, and avoid presenting an arbitrary floating end point as solved inverse kinematics.'],
  ['rosenbrock', 'Optimization in a curved valley', 'Machine learning', '3d', 'Show actual gradient descent with line search on a scaled Rosenbrock loss surface. Draw computed iterates and their connecting trajectory on the same sampled surface, including slow movement along the curved valley. Distinguish this two-parameter example from a full high-dimensional network.'],
  ['attention', 'Attention matrix and token mixing', 'Computing', '2d', 'Show a small concrete query-key dot-product matrix, row-wise softmax weights and weighted value mixing for one selected token. Choose reproducible numeric vectors; connect one highlighted matrix row to the resulting mixed vector without crowding every number onto screen.'],
  ['dijkstra', 'Weighted shortest-path frontier', 'Computing', '2d', 'Animate Dijkstra on a nontrivial planar weighted graph with at least twelve vertices. Show the actual priority order, distance relaxation and recovered path between two nodes. Keep edge weights readable and animate only the active frontier; never imply breadth-first search is sufficient for unequal weights.'],
  ['terrain', 'Textured river valley', 'Spatial worlds', '3d', 'Build a continuous terrain mesh with ridges and a connected river valley, using meaningful elevation colors and restrained rock/grass/water materials. Trace a downhill water path from the same terrain function so it follows the valley rather than tunneling through hills. State that terrain and flow are procedural illustrations.'],
  ['voxel', 'Voxel excavator at work', 'Spatial worlds', '3d', 'Show an original block-built tracked excavator digging a small earth bank. Coherent boom-stick-bucket joints, planted tracks and bucket contact must precede removal of a few soil blocks. Use restrained voxel soil and metal textures; finish with the loaded bucket raised and machine intact.'],
] as const;

export const showcasePrompt = (topic: typeof showcaseTopics[number]) =>
  `Create exactly one 20-second silent single-scene visualization showcase: ${topic[1]}. ${topic[4]} ` +
  `Use ${topic[3].toUpperCase()} because this showcase specifically tests that representation. Prioritize a detailed, correct, recognizable construction and one meaningful operation, with a short final hold. ` +
  `Use the existing 3Blue1Brown-inspired visual language: dark open canvas, restrained stable colors, readable local labels, deliberate motion and no explanatory slide deck. ` +
  `No narration, title card, outro card or wall of text. The host provides a synthetic silent timing packet; there are no spoken words to synchronize. Preserve its audio asset ID and exact duration. ` +
  `Use the real animlib capabilities and available production tools. Do not replace the requested complex construction with a generic icon. Distinguish schematic/idealized geometry from measured data. No interactive controls in this batch; allow orbit where appropriate for 3D.`;
