import csv, html, json, re
from pathlib import Path

B=Path(__file__).resolve().parent
inventory=list(csv.DictReader((B/'corpus-inventory.csv').open(encoding='utf-8')))
bykey={r['video']:r for r in inventory}
def link(key,sec,label):
    u=bykey[key]['video_url']
    if u:u+=('&' if '?' in u else '?')+f't={sec}'
    else:u=bykey[key]['caption_url']
    return f'<a href="{html.escape(u)}">{html.escape(label)}</a>'
def p(s):return f'<p>{s}</p>'

findings=[
('1. Build a reason to care before building the machinery.',
 'Openings establish an explanatory debt: a result that looks impossible, a capability whose mechanism is unclear, or a familiar formula whose meaning is missing. The eventual lesson must repay that specific debt. This is not a universal rule that every video opens with a puzzle: sequels often begin with a recap and an explicit local objective.',
 [('2020/hamming-codes',3,'Hamming codes, 00:03–02:28: scratched media → naive triple copies → redundancy cost → a much more efficient target.'),('2022/borwein',0,'Borwein integrals, opening: a repeated result stops holding; the break becomes the thing to explain.'),('2024/attention',0,'Attention, 00:00–01:59: prior-chapter recap, then why contextual updates are needed.')]),
('2. A setting is usually a manipulable problem world.',
 'He specifies objects, allowed changes, an invariant or constraint, and a target. The setting need not be a real-life story: a grid of bits, a circle with chords, a moving vector, or a graph of candidate states works. This makes later words such as “change,” “same,” and “this” operationally precise. An analogy is especially useful when it gives a rule to manipulate, rather than only a resemblance to admire.',
 [('2020/chessboard-puzzle',239,'Chessboard puzzle, 03:59–06:58: coins become coordinates; flips become cube edges; strategies become colorings.'),('2015/eulers-characteristic-formula',90,'Euler characteristic, 01:30–02:34: traveling and buying edges gives cycles and spanning trees concrete rules.'),('2020/groups-and-monsters',52,'Group theory, 00:52–03:06: change which structure must be preserved and the allowed actions change.'),('2017/chain-rule-and-product-rule',149,'Derivative rules, 02:29–10:00: addition gets stacked bars, multiplication an area, and composition linked number lines. Representation changes to match the operation.')]),
('3. Choose the smallest example that still contains the mechanism.',
 'Small examples reduce simultaneous bookkeeping while preserving the reason the general construction works. They are not merely easy numerical exercises. A two-coin board teaches a representation before a three-coin board exposes its obstruction. A 16-bit block makes four parity questions visible. A slow signal makes rotations trackable. The general case reuses relationships discovered in that manageable case.',
 [('2020/chessboard-puzzle',244,'Chessboard, 04:04–06:19: two squares → square of states → three squares → cube of states.'),('2020/hamming-codes',256,'Hamming codes, 04:16–05:13: a 16-bit working model and an explicitly deferred boundary case.'),('2018/fourier-transforms',160,'Fourier transform, 02:40–03:34: 3 Hz signal and finite time window, then an independently chosen winding rate.')]),
('4. Intuition and calculation form a loop, not separate halves.',
 'A frequent order is concrete situation → representation → qualitative prediction → calculation → reinterpreted result. But the order can reverse: a valid analytic argument may arrive first, followed by a visual explanation of why it should feel plausible. Numbers also test whether a qualitative account is enough. The robust finding is repeated translation between representations, not “avoid formulas” or “always put all equations last.”',
 [('2015/music-and-measure-theory',426,'Music and measure theory, 07:06–11:22: analytic covering construction, explicit residual confusion, then zoom-based reconciliation.'),('2020/hamming-codes-2',666,'Hamming codes part 2, 11:06–12:23: compares representations for hand computation, hardware, software, and intuition.'),('2023/gaussian-convolution',374,'Gaussian convolution, 06:14–07:23: rotational symmetry explains shape while a geometric scale correction remains necessary.'),('2017/eulers-number',219,'Euler’s number, 03:39–04:07: explicitly uses numerical patterns after acknowledging the lack of the desired geometric explanation.')]),
('5. Pacing follows conceptual novelty.',
 'New operations receive setup, explicit mapping, a worked case, interpretation, and often a checkpoint. Repeated operations are compressed once their grammar is familiar. Recaps summarize what a construction now means; they are not merely a list of topics. Large transitions often announce what has been earned and what remains unexplained. Timed captions support these sequences, but cannot establish editing rhythm or visual hold lengths.',
 [('2020/hamming-codes',534,'Hamming codes, 08:54–11:10 explains column checks and their combination; 11:11–11:41 dispatches analogous row checks.'),('2018/fourier-transforms',404,'Fourier transform, 06:44–07:02 recaps three linked representations before extending them.'),('2022/subsets-puzzle',1593,'Subset puzzle, around 26:33: recap after several abstract bridges accumulate.')]),
('6. Audience interaction asks for work, with different levels of difficulty.',
 'Separate at least four moves: predict a visible consequence; execute a manageable example; connect two representations; justify why a construction works. These are stronger than rhetorical questions such as whether something is interesting. He also anticipates objections and explicitly normalizes confusion. The inclusive voice alternates among personal curiosity, joint investigation, and a direct task for the viewer.',
 [('2020/hamming-codes',149,'Hamming codes, 02:29–02:46 explicitly frames the lesson as guided invention; 16:12–19:14 asks viewers to encode and decode.'),('2020/chessboard-puzzle',701,'Chessboard, 11:41–12:52: try a coloring, then turn an intuition into a proof.'),('2024/attention',100,'Attention, 01:40–01:59 acknowledges difficulty before introducing behavioral examples.')]),
('7. Visual references function as instructions and bindings.',
 '“This” is often followed by an object and its mathematical job, an operation to perform, or a consequence to observe. The binding matters: a dot is not just a dot, but a center of mass; a column is not just screen layout, but a particular class of indices. Speech teaches the correspondence and then uses it as shared vocabulary. Attention cues are useful when they identify what changes or what relation to compare.',
 [('2018/fourier-transforms',299,'Fourier transform, 04:59–06:32: center-of-mass dot → varied winding rate → displacement → plotted statistic.'),('2020/hamming-codes-2',134,'Hamming codes part 2, 02:14–03:17: attend to one bit of labels, highlight matching positions, recover parity groups.'),('2017/tattoos-on-math',88,'Trig geometry, 01:28–04:23: distances and corresponding similar-triangle sides are verbally identified before the ratio argument.')]),
('8. A strong visualization makes the inference available.',
 'The picture often changes the form of the problem so the desired relationship becomes inspectable: composition becomes successive transformations, a count becomes a bijection, an algorithm becomes motion or grouped positions, a probability becomes restricted area. The visual is doing explanatory work when the viewer can use it to predict or reconstruct a step. It is not sufficient that an animation merely changes when a parameter changes.',
 [('2015/moser',132,'Circle division, 02:12–02:41: intersection points correspond one-to-one with quadruples of boundary points.'),('2020/chessboard-puzzle',777,'Chessboard, 12:57–15:23: double-counting cube neighbors creates an obstruction to any strategy.'),('2018/fourier-transforms',529,'Fourier transform, 08:49–10:35: the same construction applied to mixed signals explains why frequency peaks separate.')]),
('9. Preserve semantic identity when changing the representation.',
 'Transitions frequently carry the same mathematical quantity into a new view. Speech explains both what remains the same and what is newly encoded. This supports a continuity-of-meaning claim; transcript evidence alone cannot prove exact object morphs, camera continuity, or persistent color choices across frames. Several videos also explicitly distinguish things that look alike but mean different things.',
 [('2020/hamming-codes-2',97,'Hamming codes part 2, 01:37–02:14: binary index labels are explicitly distinguished from transmitted message bits.'),('2023/convolutions2',1409,'Convolution, around 23:29–24:44: one parameter drives two views; geometric slice length needs a correction.'),('2023/clt',1305,'Central limit theorem, around 21:45: bar semantics change from height to area and the change is explained.'),('2016/nonsquare-matrices',60,'Nonsquare matrices, 01:00–01:21: keeps input/output spaces separate and deliberately declines the usual moving-between treatment.')]),
('10. Equations usually compress operations already assigned meaning.',
 'A formula can arrive early as the mystery or destination. When developed in detail, its terms are attached to earlier operations: rotate, scale, average; add effects along a dependency path; sum weights over possibilities. He often moves from an individual example to the same procedure with symbolic names. The goal is a readable computation, not an equation-free story.',
 [('2018/fourier-transforms',824,'Fourier transform, 13:44–16:05: winding becomes multiplication by a complex exponential; sampled averaging becomes an integral; normalization is then distinguished.'),('2017/backpropagation-calculus',191,'Backpropagation calculus, around 03:11–08:23: chains of small changes become products and sums of derivatives.'),('2021/quick-eigen',0,'Quick eigenvalue trick: exact computation is the central task from the outset.')]),
('11. Tell viewers where the representation stops being literal.',
 'He repeatedly identifies a model’s scope: drawings cannot show infinite detail; projected geometry is not the full high-dimensional object; a neural-network example may represent intended behavior rather than observed learned features; a simulation is not the real world. Counterexamples and corrections are part of the explanatory style. These caveats qualify visual intuition rather than removing its usefulness.',
 [('2015/inventing-math',735,'Inventing math, 12:15–12:24: apparent Euclidean closeness in the drawing is not the proposed distance.'),('2022/visual-proofs',0,'Visual proofs: plausible diagrams become traps whose assumptions must be diagnosed.'),('2017/gradient-descent',861,'Gradient descent, around 14:21: observed trained features do not match the preceding hoped-for feature hierarchy.'),('2020/epidemic-simulations',126,'Epidemic simulations, 02:06–02:40 and 12:22–12:44: limits of the toy model are stated.')]),
('12. Endings revisit the motivating itch or sharpen the next question.',
 'An exact answer is sometimes not enough: he returns to why the starting pattern was tempting or why a phenomenon should have been possible at all. Other endings deliberately leave a deeper proof, mechanism, or implementation to a sequel. Some are recaps; some are open questions. “Everything closes with a complete proof” and “never recap” would both be false generalizations.',
 [('2015/moser',398,'Circle division, 06:38–08:42: after obtaining the formula, explain the powers-of-two resemblance, then recap.'),('2020/hamming-codes',1155,'Hamming codes, 19:15–19:41: hand-solvable mechanism leads to a promise of one-line implementation.'),('2020/groups-and-monsters',1182,'Group theory, 19:42–21:25: unresolved structure and limits of clean final answers remain part of the ending.')]),
]

language=[
('Locate','A particular point, group, column, region, or side.','Establish an unambiguous referent before making a claim.','2020/hamming-codes-2',134),
('Assign meaning','A mark represents a quantity; an axis or region has a declared interpretation.','Give the viewer the decoding rule.','2018/fourier-transforms',299),
('Manipulate','Rotate, wrap, shift, stretch, flip, slide, change a parameter.','Make the mathematical operation observable.','2018/fourier-transforms',175),
('Predict','Ask what would change before showing or describing the outcome.','Turn the display into an experiment the viewer can reason about.','2020/epidemic-simulations',189),
('Compare','Read two representations or two controlled cases together.','Expose an invariant, correspondence, or causal contrast.','2020/epidemic-simulations',1130),
('Compress','After the operation is understood, write or name it compactly.','Make formal notation a handle on known behavior.','2020/hamming-codes-2',493),
('Reinterpret','Keep the object or relationship, change what it counts or represents.','Enable an inference unavailable in the original framing.','2020/chessboard-puzzle',396),
('Qualify','Identify an approximation, omitted dimension, simplification, or ambiguous mark.','Prevent the visual encoding from being mistaken for a stronger claim.','2015/music-and-measure-theory',580),
]

def render(evidence):
    stats=json.loads((B/'corpus-statistics.json').read_text())['main_explainers']
    body='<h1>How 3Blue1Brown builds explanations</h1><p class="dek">Transcript study • 2015–2024 archive • prepared 10 October 2026</p>'
    body+=p('<strong>Central finding:</strong> the recurring unit is a guided act of reasoning: establish a question, construct a representation, ask for an operation or prediction, inspect its consequence, and translate that consequence into a more general statement. Visuals frequently provide the objects and operations of the argument.')
    body+='<nav><a href="#method">Scope</a><a href="#findings">Findings</a><a href="#language">Visual language</a><a href="#example">Detailed sequence</a><a href="#application">Writing rules</a><a href="#catalog">117-video evidence index</a></nav>'
    body+='<h2 id="method">Scope and limits</h2>'
    body+=p(f'153 archived English caption files retrieved; 150 contain text, three are empty. A stated filtering rule selects 117 substantive explainers, containing {stats["words"]:,} tokenized words and approximately {stats["caption_span_hours"]} hours between first and last subtitle times. Four research readers (main agent and three subagents) fully read those 117 transcripts. Other formats were inventoried but not equivalently studied: shorts, live lessons, Q&amp;As, speeches, announcements, songs, and event videos. One explicitly credited adaptation remains included and is identified in its evidence note.')
    body+=p('Source: <a href="https://github.com/3b1b/captions/tree/0bce59666e3b16b449d414da253beb11257b5da6">creator-owned caption archive at immutable commit 0bce596…</a>. The current repository describes migration to Criblate; this historical snapshot is not a complete current channel census. No 2025–2026 claim is made. No videos were watched for this study: object correspondence, order, and instructions are supported by narration; exact motion, composition, cuts, sound, or hold duration remain unverified. Caption errors include duplicated text, missing mathematical symbols, reversed intervals, and empty files. Linked times are approximate navigation aids.')
    body+=p('This is qualitative pattern analysis with reproducible lexical counts, not a blinded content-coding study or an experiment measuring learning. Interpretations of pedagogical function are analytical inferences. Avoid converting recurring examples into universal rules or exact percentages of explanatory strategies.')
    body+='<table><thead><tr><th>Literal transcript marker</th><th>Videos among 117</th><th>What this establishes</th></tr></thead><tbody>'
    for key,label,meaning in [('think_of','think of','Representation prompts recur.'),('notice','notice / noticing','Explicit attention cues recur.'),('imagine','imagine / imagining','Mental construction language recurs.'),('explicit_pause','pause / pausing','Pause vocabulary appears in a substantial minority; context still matters.'),('zoom','words beginning zoom','Scale changes are sometimes narrated explicitly.')]:
        body+=f'<tr><td>{label}</td><td>{stats["lexical_markers"][key]["videos_with_match"]}/117</td><td>{meaning}</td></tr>'
    body+='</tbody></table>'+p('These are case-insensitive regex hits anywhere in a transcript, including incidental remarks and outros. They are not counts of validated teaching moves. Definitions and per-video counts are saved in analyze_corpus.py and corpus-inventory.csv.')
    body+='<h2 id="findings">Twelve findings</h2>'
    for title,claim,sources in findings:
        body+='<section><h3>'+title+'</h3>'+p(claim)+'<ul>'+''.join('<li>'+link(*x)+'</li>' for x in sources)+'</ul></section>'
    body+='<h2 id="language">How narration talks to the visualization</h2>'+p('These are analytical categories, not a quotation list or a prescribed script. The important feature is the job a phrase performs in relation to a visible object.')
    body+='<table><thead><tr><th>Move</th><th>Typical content</th><th>Function</th><th>Example</th></tr></thead><tbody>'
    for a,b,c,key,sec in language:body+=f'<tr><td>{a}</td><td>{b}</td><td>{c}</td><td>{link(key,sec,key.split("/")[1])}</td></tr>'
    body+='</tbody></table>'
    body+='<h2 id="example">One sequence in detail: Fourier transform</h2>'
    body+=p('This is a particularly clear example of linked representations carrying the argument. The timeline describes narrated progression, not independently observed screen editing.')
    phases=[(4,'00:04–00:49','Preview the destination and state a dual audience: newcomers and people who already know the topic.'),(50,'00:50–02:29','Sound becomes pressure over time; mixtures motivate the need to recover component frequencies.'),(160,'02:40–04:36','Reduce to a slow signal; define wrapping, vector length, winding rate, and reference marks.'),(277,'04:37–06:32','Notice alignment, introduce a center-of-mass statistic, and graph its response to winding frequency.'),(404,'06:44–08:38','Recap three linked representations; explain an artificial offset; repeat with a second frequency.'),(519,'08:39–10:35','Mix the signals, observe separated peaks, and invite verification of additivity.'),(636,'10:36–11:54','Use the constructed mechanism for sound filtering, while flagging provisional definitions.'),(715,'11:55–16:05','Add the missing complex coordinate, encode rotation algebraically, turn averaging into integration, and distinguish normalization.')]
    body+='<table><thead><tr><th>Approximate span</th><th>Narrated task</th></tr></thead><tbody>'+''.join(f'<tr><td>{link("2018/fourier-transforms",s,t)}</td><td>{d}</td></tr>' for s,t,d in phases)+'</tbody></table>'
    body+=p('The general lesson is not that every video should spend twelve minutes before introducing formalism. It is that formalism becomes easier to interpret when its operations already have identifiable referents. The different rates are distinguished before either becomes a source of silent ambiguity.')
    body+='<h2 id="application">Practical writing rules derived from the evidence</h2>'
    body+=p('These are proposed applications of the findings, not claims that Sanderson follows a fixed production checklist.')
    rules=['State exactly what the viewer should be able to explain at the end, and create that need early.','Choose a working world with clear objects, allowed operations, and a preserved relationship.','Teach the visual encoding before using it to carry an inference.','Make a first example small enough to reason through, but rich enough to contain the central mechanism.','Place a prediction or interpretation task immediately before its consequence.','When an operation is new, explain each correspondence; when repeated, compress the narration.','Introduce notation by pointing back to operations or quantities already understood.','Carry the same quantity across representations and name the correspondence explicitly.','Use numerical examples and limiting cases to test the qualitative story.','State what a model exaggerates, omits, approximates, or merely hopes to represent.','After getting an answer, check whether the original source of curiosity has actually been explained.','Assess exact timing, motion, and composition through video inspection separately; transcripts cannot settle them.']
    body+='<ol>'+''.join('<li>'+x+'</li>' for x in rules)+'</ol>'
    body+='<h2 id="catalog">Video-by-video evidence index</h2>'+p('Each entry records a full transcript read and analytical notes. Open the original video at the approximate times in the note; the immutable caption link permits source checking. Slugs identify the exact archived files, rather than guessed current YouTube titles.')
    for key in sorted(evidence):
        r=bykey[key]
        media_label='Original video' if r['video_url'] else 'Source (video URL absent from archive)'
        body+=f'<details><summary>{html.escape(key)}</summary><p>{html.escape(evidence[key])}</p><p>{link(key,0,media_label)} · <a href="{html.escape(r["caption_url"])}">Timed caption source</a></p></details>'
    body+=p('Research artifacts: <a href="corpus-inventory.csv">corpus inventory</a> · <a href="corpus-statistics.json">counts</a> · <a href="analyze_corpus.py">counting script</a> · <a href="evidence-index.csv">117-video evidence index</a>.')
    css='body{font:17px/1.65 system-ui,sans-serif;color:#20262c;background:#fcfbf7;max-width:1060px;margin:50px auto;padding:0 24px}h1{font-size:42px;line-height:1.15}h2{margin-top:52px;border-top:1px solid #c9d0d3;padding-top:25px}h3{font-size:22px;margin-top:34px}.dek{color:#53646d}nav{display:flex;flex-wrap:wrap;gap:18px;padding:18px 0;border-block:1px solid #c9d0d3}a{color:#175c84;text-underline-offset:3px}table{width:100%;border-collapse:collapse;font-size:15px}th,td{text-align:left;vertical-align:top;border-bottom:1px solid #d6dcdd;padding:12px}th{background:#edf2f1}li{margin:8px 0}details{border-bottom:1px solid #d6dcdd;padding:12px 0}summary{cursor:pointer;font-weight:600}details p{font-size:15px}section{break-inside:avoid}@media print{body{font-size:11pt;margin:0;max-width:none}nav{display:none}details{display:block}a{color:inherit}}'
    (B/'3blue1brown-transcript-study.html').write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>3Blue1Brown transcript study</title><style>'+css+'</style><body>'+body+'</body></html>',encoding='utf-8')
    with (B/'evidence-index.csv').open('w',encoding='utf-8',newline='') as f:
        w=csv.DictWriter(f,fieldnames=['video','evidence','video_url','caption_url']);w.writeheader()
        for key,note in sorted(evidence.items()):w.writerow({'video':key,'evidence':note,'video_url':bykey[key]['video_url'],'caption_url':bykey[key]['caption_url']})

if __name__=='__main__':
    evidence=json.loads((B/'merged-evidence.json').read_text(encoding='utf-8'))
    wanted={r['video'] for r in inventory if r['subset']=='main_explainers'}
    assert set(evidence)==wanted,{'missing':sorted(wanted-set(evidence)),'extra':sorted(set(evidence)-wanted)}
    render(evidence)
    print(f'Rendered report with {len(evidence)} full-read evidence entries.')
